# Site Settings
locale                   : "en-US"
title                    : "Project Lab"
title_separator          : "-"
name                     : "Austin Lundeby"
description              : ""
masthead_title           : "Austin Lundeby"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.15.1"
