# Site Settings
#name: Austin Lundeby
title: Austin Lundeby
masthead_title: Austin Lundeby

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.15.1"
