# Site Settings
locale                   : "en-US"
title_separator          : "-"
title                    : "Austin Lundeby" # Appended to page title after separator
name                     : "Austin Lundeby"
description              : ""
masthead_title           : "Austin Lundeby"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.15.1"

include: ["_pages"]

host: 0.0.0.0

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
